import { config } from "@/wagmi/config";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { WagmiProvider, cookieToInitialState } from "wagmi";
import "./globals.css";
import { ContextProvider } from "@/wagmi/context";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zurf Balance",
  description: "Generated by Matias Palomo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <ContextProvider initialState={initialState}>
        <body className={inter.className}>{children}</body>
      </ContextProvider>
    </html>
  );
}
